/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils; 
/**
 *
 * @author Roger Simanjuntak
 */
public class MenuHistory extends javax.swing.JFrame {
    public static DefaultTableModel tb;
    public static int id;

    /**
     * Creates new form MenuHistroy
     */
  
    public MenuHistory() {
        initComponents();
        DisplayTr();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        
    }  
    int myNorek;
    public MenuHistory(int no_rek) {
        initComponents();
        myNorek = no_rek;
    }
    Connection con = null;
    PreparedStatement pst;
    ResultSet Rs = null;
    Statement St = null;
    int oldSaldo;
    public void DisplayTr()
    {
        tb = new DefaultTableModel();
        tb.addColumn("no_rek");
        tb.addColumn("type");
        tb.addColumn("tdate");
        tb.addColumn("jumlah");
        User_Table.setModel(tb);
        
        
 
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbatm","root","");  
                St = con.createStatement();
                String query ="select * from transactiontbl where no_rek"+myNorek+"";
                Rs = St.executeQuery(query);
                User_Table.setModel(DbUtils.resultSetToTableModel(Rs));
                int index = 0;
        while(Rs.next()){    
        User_Table.getModel().setValueAt(Rs.getString("no_rek"), index, 0);
        User_Table.getModel().setValueAt(Rs.getString("type"), index, 1);
        User_Table.getModel().setValueAt(Rs.getString("tdate"), index, 2);
        User_Table.getModel().setValueAt(Rs.getString("jumlah"), index, 3);
        index++;
        }
        St.close();
        Rs.close();
        con.close();
        
        } catch (Exception DBException) {
            JOptionPane.showMessageDialog(this,"FAILED","ERROR",JOptionPane.ERROR_MESSAGE);
            System.err.println("Error:" +DBException);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        KeluarMenu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        User_Table = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtampil = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jhapus = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/9631.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Keluar dari Menu Bank ?");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 210, 20));

        KeluarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/exit_icon-icons.com_7097_10x10-removebg-preview.png"))); // NOI18N
        KeluarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KeluarMenuMouseClicked(evt);
            }
        });
        jPanel2.add(KeluarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/9631.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 80));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(255, 153, 51));
        jScrollPane2.setForeground(new java.awt.Color(0, 0, 0));

        User_Table.setBackground(new java.awt.Color(255, 255, 255));
        User_Table.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        User_Table.setForeground(new java.awt.Color(0, 0, 0));
        User_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nomor Rekening", "Tipe", "Tanggal", "Jumlah"
            }
        ));
        User_Table.setEnabled(false);
        jScrollPane2.setViewportView(User_Table);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 610, 410));

        jLabel13.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Ke Menu Utama");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, 110, 20));

        jLabel17.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Hapus");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, 120, 20));

        jLabel16.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tampilkan");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, 120, 20));

        jLabel14.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Kembali");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 60, 20));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/output-onlinegiftools (5).gif"))); // NOI18N
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 70, 40));

        jtampil.setBackground(new java.awt.Color(153, 255, 51));
        jtampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtampilActionPerformed(evt);
            }
        });
        jPanel3.add(jtampil, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 190, 60));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 190, 60));

        jhapus.setBackground(new java.awt.Color(255, 102, 102));
        jhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jhapusMouseClicked(evt);
            }
        });
        jhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhapusActionPerformed(evt);
            }
        });
        jPanel3.add(jhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 190, 60));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Anda Menabung, Kami  Kenyang");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 210, 40));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/9631.png"))); // NOI18N
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 360, 90, 80));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Percayakan Kepada Kami,");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 190, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/5570863.jpg"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 490));

        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Kembali");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 60, 20));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-left-arrow-30.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 70, 40));

        jLabel12.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Ke Menu Utama");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, -1, 10));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Anda Menabung, Kami  Kenyang");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 210, 40));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Percayakan Kepada Kami,");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 190, 40));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/9631.png"))); // NOI18N
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 90, 80));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KeluarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeluarMenuMouseClicked
        System.exit(0);
    }//GEN-LAST:event_KeluarMenuMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    new Main(myNorek).setVisible(true);
    this.dispose();
                     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtampilActionPerformed
        // TODO add your handling code here:
        try {
            String url = "jdbc:mysql://localhost/dbatm";
            String user = "root";
            String pass = "";           
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(url, user, pass);
            Statement stmt = con.createStatement();
            String query = "SELECT * FROM transactiontbl no_rek"+myNorek+"";
            ResultSet rs = stmt.executeQuery(query);
            int index = 0;
            
        while(rs.next()){    
        User_Table.getModel().setValueAt(rs.getString("no_rek"), index, 0);
        User_Table.getModel().setValueAt(rs.getString("type"), index, 1);
        User_Table.getModel().setValueAt(rs.getString("tdate"), index, 2);
        User_Table.getModel().setValueAt(rs.getString("jumlah"), index, 3);
        index++;
        }
        rs.close();
        stmt.close();
        con.close();
        
        } catch (Exception DBException) {
            JOptionPane.showMessageDialog(this,"FAILED","ERROR",JOptionPane.ERROR_MESSAGE);
            System.err.println("Error:" +DBException);
        }
    }//GEN-LAST:event_jtampilActionPerformed

    private void jhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhapusActionPerformed
     // TODO add your handling code here:
        DefaultTableModel DT = (DefaultTableModel) User_Table.getModel();
         //Delete Row in Table
        if(User_Table.getSelectedRowCount()==1) {
            DT.removeRow(User_Table.getSelectedRow());
        }else {
            if(User_Table.getRowCount()==1){
                //if table is empty, display message:
                JOptionPane.showMessageDialog(this,"Table is empty");
            }else {
                //table not empty, but row isn't selected or multiple row is selected
           JOptionPane.showMessageDialog(this,"Select a single row");  
            }
        }
    }//GEN-LAST:event_jhapusActionPerformed

    private void jhapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jhapusMouseClicked
    // TODO add your handling code here:
         try {           
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbatm","root","");
            St = con.createStatement();
            String update;
            update = "DELETE FROM transactiontbl WHERE no_rek ='" + myNorek+"'";
            St = con.createStatement();
            St.executeUpdate(update);
            JOptionPane.showMessageDialog(this, "SUCCESSFUL","INFORMATION",JOptionPane.INFORMATION_MESSAGE);         
        } 
        catch (Exception DBException) {
            JOptionPane.showMessageDialog(this,"UNSUCCESSFUL","ERROR",JOptionPane.ERROR_MESSAGE);
            System.err.println("Error:" +DBException);
        }
    }//GEN-LAST:event_jhapusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KeluarMenu;
    private javax.swing.JTable User_Table;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jhapus;
    private javax.swing.JButton jtampil;
    // End of variables declaration//GEN-END:variables
}
